/**
 * 린다이어트 의약품 종합 마스터 DB (대규모 확장판)
 * - 국내 주요 처방/일반의약품 500+ 품목 전수 매핑
 * - [병용 불가] 67종 및 [주의 필요] 100여종 성분 100% 매칭
 */

const API_SERVICE_KEY = "TQlkY3w0pbDwrIkmNiO6dCr7YqfC2RdGfi8O%2FJDIqGuIfAHJJHup87%2FZ2xSKzpEXZNb0gjvqi%2F0BR%2BUwEO86BA%3D%3D";

// 1. 금기(PROHIBITED) 및 주의(CAUTION) 전체 성분 DB (연구진 의견 100% 수록)
const ALL_DRUG_INGREDIENTS = [
  // === [병용 불가 (PROHIBITED)] ===
  { id: "acebrophylline", koreanName: "아세브로필린", englishName: "Acebrophylline", category: "호흡기/기관지확장제", status: "PROHIBITED", opinion: "PDE 억제 + 아데노신 길항 → 에페드린과 심장 자극 상승, 부정맥·경련 위험", commonBrands: ["아세브론", "에어브론", "브론코", "서브론"] },
  { id: "aminophylline", koreanName: "아미노필린", englishName: "Aminophylline", category: "호흡기/천식치료제", status: "PROHIBITED", opinion: "PDE 억제 + 아데노신 길항 → 에페드린과 심장 자극 상승, 부정맥·경련 위험", commonBrands: ["아미노필린"] },
  { id: "amitriptyline", koreanName: "아미트리프틸린염산염", englishName: "Amitriptyline Hydrochloride", category: "삼환계 항우울제(TCA)", status: "PROHIBITED", opinion: "노르에피네프린 재흡수 차단 + 에페드린 → 카테콜아민 축적, 고혈압 위기, 부정맥 위험", commonBrands: ["에나폰"] },
  { id: "amoxapine", koreanName: "아목사핀", englishName: "Amoxapine", category: "항우울제", status: "PROHIBITED", opinion: "노르에피네프린 재흡수 차단 + 에페드린 → 카테콜아민 축적, 고혈압 위기, 부정맥 위험" },
  { id: "bambuterol", koreanName: "밤부테롤염산염", englishName: "Bambuterol Hydrochloride", category: "기관지확장제/천식", status: "PROHIBITED", opinion: "교감신경계 상가 작용 → 심박수 증가, 저칼륨혈증, 부정맥 위험", commonBrands: ["밤벡"] },
  { id: "bupropion", koreanName: "부프로피온염산염", englishName: "Bupropion Hydrochloride", category: "항우울제/금연보조/식욕억제", status: "PROHIBITED", opinion: "노르에피네프린·도파민 재흡수 억제 + 에페드린 → 경련 역치 저하, 고혈압 위기 위험", commonBrands: ["웰부트린", "콘트라브", "웰콘트"] },
  { id: "cabergoline", koreanName: "카베르고린", englishName: "Cabergoline", category: "도파민작용제/유즙분비억제", status: "PROHIBITED", opinion: "5-HT2B 수용체 작용 → 심장 판막 섬유화 위험 + 에페드린 심장 부하 추가 → 심혈관 위험 증폭", commonBrands: ["카버락틴", "도스티넥스"] },
  { id: "caffeine_anhydrous", koreanName: "카페인무수물", englishName: "Caffeine Anhydrous", category: "중추신경흥분/복합진통제", status: "PROHIBITED", opinion: "PDE 억제 + 아데노신 길항 → 에페드린과 심장 자극 상승, 부정맥·경련 위험", commonBrands: ["게보린", "펜잘", "그날엔", "판피린", "판콜"] },
  { id: "carteolol", koreanName: "카르테올롤염산염", englishName: "Carteolol Hydrochloride", category: "안과/녹내장치료제", status: "PROHIBITED", opinion: "비선택적 베타차단 + 에페드린 → 비길항 알파 자극으로 심한 고혈압 위험", commonBrands: ["미케란"] },
  { id: "clomipramine", koreanName: "클로미프라민염산염", englishName: "Clomipramine Hydrochloride", category: "항우울제/강박장애", status: "PROHIBITED", opinion: "노르에피네프린 재흡수 차단 + 에페드린 → 카테콜아민 축적, 고혈압 위기, 부정맥 위험", commonBrands: ["그process"] },
  { id: "clonidine", koreanName: "클로니딘", englishName: "Clonidine", category: "혈압약/ADHD", status: "PROHIBITED", opinion: "클로니딘은 반동성 고혈압 위험이 높은 약물로 에페드린 병용 시 위험 증폭", commonBrands: ["캡베이", "카타프레스"] },
  { id: "cyclosporine", koreanName: "사이클로스포린", englishName: "Cyclosporine", category: "면역억제제", status: "PROHIBITED", opinion: "신독성·고혈압 유발약 + 에페드린의 혈관수축·혈압상승 → 신독성·고혈압 악화", commonBrands: ["산디문", "사이폴엔"] },
  { id: "dasatinib", koreanName: "다사티닙", englishName: "Dasatinib", category: "항암제/표적치료제", status: "PROHIBITED", opinion: "QT 간격 연장 유발 + 에페드린 심장 자극 → 중증 부정맥 위험; 악성 종양 치료 중인 환자에게 다이어트 처방 부적절", commonBrands: ["스프라이셀"] },
  { id: "desvenlafaxine", koreanName: "데스벤라팍신", englishName: "Desvenlafaxine", category: "SNRI 항우울제", status: "PROHIBITED", opinion: "세로토닌·노르에피네프린 재흡수 차단 + 에페드린 → 세로토닌 증후군 + 고혈압 이중 위험", commonBrands: ["프리스틱"] },
  { id: "diethylaminoethyltheophylline", koreanName: "디에틸아미노에틸테오필린염산염", englishName: "Diethylaminoethyltheophylline", category: "기관지확장제", status: "PROHIBITED", opinion: "PDE 억제 + 아데노신 길항 → 에페드린과 심장 자극 상승, 부정맥·경련 위험" },
  { id: "dl_methylephedrine", koreanName: "DL-메틸에페드린", englishName: "DL-Methylephedrine", category: "감기약/진해거담제", status: "PROHIBITED", opinion: "동일 기전 약물 중복 → 과도한 교감신경 자극, 고혈압 위기, 부정맥, 뇌졸중 위험", commonBrands: ["코푸", "코대원", "화이투벤", "판콜", "판피린"] },
  { id: "doxepin", koreanName: "독세핀염산염", englishName: "Doxepin Hydrochloride", category: "삼환계 항우울제/수면제", status: "PROHIBITED", opinion: "노르에피네프린 재흡수 차단 + 에페드린 → 카테콜아민 축적, 고혈압 위기, 부정맥 위험", commonBrands: ["사일레노"] },
  { id: "doxofylline", koreanName: "독소필린", englishName: "Doxofylline", category: "기관지확장제/천식", status: "PROHIBITED", opinion: "PDE 억제 + 아데노신 길항 → 에페드린과 심장 자극 상승, 부정맥·경련 위험", commonBrands: ["렉시핀", "액시마", "독소마", "앤도스", "슈로피", "독시마", "덱시필린", "독소필"] },
  { id: "duloxetine", koreanName: "둘록세틴염산염", englishName: "Duloxetine Hydrochloride", category: "SNRI 항우울제/신경통", status: "PROHIBITED", opinion: "세로토닌·노르에피네프린 재흡수 차단 + 에페드린 → 세로토닌 증후군 + 고혈압 이중 위험", commonBrands: ["심발타", "듀록셉", "드록틴"] },
  { id: "ephedrine", koreanName: "에페드린", englishName: "Ephedrine", category: "교감신경흥분제", status: "PROHIBITED", opinion: "동일 성분 중복 투여 → 과량 투여 위험" },
  { id: "epinephrine", koreanName: "에피네프린", englishName: "Epinephrine", category: "응급혈관수축제", status: "PROHIBITED", opinion: "동일 기전 약물 중복 → 과도한 교감신경 자극, 고혈압 위기, 부정맥 위험", commonBrands: ["에피펜"] },
  { id: "ergotamine", koreanName: "에르고타민타르타르산염", englishName: "Ergotamine Tartrate", category: "편두통치료제", status: "PROHIBITED", opinion: "강력한 혈관수축 작용 + 에페드린 → 심각한 말초·관상동맥 허혈 위험", commonBrands: ["크래밍", "카펠고트"] },
  { id: "escitalopram", koreanName: "에스시탈로프람옥살산염", englishName: "Escitalopram Oxalate", category: "SSRI 항우울제/공황장애", status: "PROHIBITED", opinion: "세로토닌 재흡수 차단 + 에페드린 → 세로토닌 증후군 위험", commonBrands: ["렉사프로", "에스시탐", "산도스에스시탈로프람"] },
  { id: "flecainide", koreanName: "플레카이니드아세트산염", englishName: "Flecainide Acetate", category: "항부정맥제", status: "PROHIBITED", opinion: "에페드린의 부정맥 유발 작용이 항부정맥 치료 효과를 무력화 → 위험한 심실 부정맥 유발 가능" },
  { id: "fluconazole", koreanName: "플루코나졸", englishName: "Fluconazole", category: "항진균제/질염/무좀약", status: "PROHIBITED", opinion: "CYP 억제 → QT 간격 연장 + 에페드린 심장 자극 → 부정맥(TdP) 위험; 마황 간독성 + 항진균제 간독성 상가" },
  { id: "fluoxetine", koreanName: "플루옥세틴염산염", englishName: "Fluoxetine Hydrochloride", category: "SSRI 항우울제/폭식증", status: "PROHIBITED", opinion: "세로토닌 증후군 위험 + CYP2D6 강력 억제로 에페드린 대사 지연 가능" },
  { id: "fluvoxamine", koreanName: "플루복사민말레산염", englishName: "Fluvoxamine Maleate", category: "SSRI 항우울제/강박장애", status: "PROHIBITED", opinion: "세로토닌 재흡수 차단 + 에페드린 → 세로토닌 증후군 위험" },
  { id: "formoterol", koreanName: "포르모테롤", englishName: "Formoterol", category: "기관지확장제/천식", status: "PROHIBITED", opinion: "교감신경계 상가 자극 → 심박수 증가, 저칼륨혈증, 부정맥 위험" },
  { id: "frovatriptan", koreanName: "프로바트립탄숙신산염", englishName: "Frovatriptan Succinate", category: "편두통치료제", status: "PROHIBITED", opinion: "혈관수축 기전 + 에페드린 혈관수축 → 관상동맥 수축, 혈관 경련 위험" },
  { id: "hydroxychloroquine", koreanName: "히드록시클로로퀸", englishName: "Hydroxychloroquine", category: "류마티스/면역조절제", status: "PROHIBITED", opinion: "QT 간격 연장 + 에페드린 심장 자극 → 부정맥 위험; 장기 복용 시 심근병증 유발 가능" },
  { id: "imipramine", koreanName: "이미프라민염산염", englishName: "Imipramine Hydrochloride", category: "삼환계 항우울제/야뇨증", status: "PROHIBITED", opinion: "노르에피네프린 재흡수 차단 + 에페드린 → 카테콜아민 축적, 고혈압 위기, 부정맥 위험" },
  { id: "itraconazole", koreanName: "이트라코나졸", englishName: "Itraconazole", category: "항진균제/손발톱무좀", status: "PROHIBITED", opinion: "CYP 억제 → QT 간격 연장 + 에페드린 심장 자극 → 부정맥(TdP) 위험; 마황 간독성 + 항진균제 간독성 상가" },
  { id: "levothyroxine", koreanName: "레보티록신나트륨수화물", englishName: "Levothyroxine Sodium", category: "갑상선호르몬제", status: "PROHIBITED", opinion: "갑상선 호르몬이 카테콜아민 감수성 증가 → 에페드린과 빈맥, 부정맥, 고혈압 위험 증폭" },
  { id: "milnacipran", koreanName: "밀나시프란염산염", englishName: "Milnacipran Hydrochloride", category: "SNRI 항우울제/섬유근육통", status: "PROHIBITED", opinion: "세로토닌·노르에피네프린 재흡수 차단 + 에페드린 → 세로토닌 증후군 + 고혈압 이중 위험" },
  { id: "mirtazapine", koreanName: "미르타자핀", englishName: "Mirtazapine", category: "항우울제/수면유도", status: "PROHIBITED", opinion: "알파2 차단으로 노르에피네프린 분비 촉진 → 에페드린과 상기 작용, 고혈압 위험" },
  { id: "moclobemide", koreanName: "모클로베미드", englishName: "Moclobemide", category: "MAO-A 억제제/항우울제", status: "PROHIBITED", opinion: "MAO-A 억제 + 에페드린 → 고혈압 위기. 교감신경 흥분제와 MAO 억제제의 가장 위험한 조합" },
  { id: "naratriptan", koreanName: "나라트립탄염산염", englishName: "Naratriptan Hydrochloride", category: "편두통치료제", status: "PROHIBITED", opinion: "혈관수축 기전 + 에페드린 혈관수축 → 관상동맥 수축, 혈관 경련 위험" },
  { id: "nortriptyline", koreanName: "노르트립틸린", englishName: "Nortriptyline", category: "삼환계 항우울제", status: "PROHIBITED", opinion: "노르에피네프린 재흡수 차단 + 에페드린 → 카테콜아민 축적, 고혈압 위기, 부정맥 위험" },
  { id: "paroxetine", koreanName: "파록세틴염산염수화물", englishName: "Paroxetine Hydrochloride", category: "SSRI 항우울제/공황장애", status: "PROHIBITED", opinion: "세로토닌 재흡수 차단 + 에페드린 → 세로토닌 증후군 위험" },
  { id: "phenylephrine", koreanName: "페닐레프린염산염", englishName: "Phenylephrine Hydrochloride", category: "비충혈제거제/혈관수축제", status: "PROHIBITED", opinion: "동일 기전 약물 중복 → 과도한 혈관수축, 고혈압 위험" },
  { id: "pilsicainide", koreanName: "필시카이니드염산염수화물", englishName: "Pilsicainide Hydrochloride", category: "항부정맥제", status: "PROHIBITED", opinion: "에페드린의 부정맥 유발 작용이 항부정맥 치료 효과를 무력화 → 위험한 심실 부정맥 유발 가능" },
  { id: "posaconazole", koreanName: "포사코나졸", englishName: "Posaconazole", category: "항진균제", status: "PROHIBITED", opinion: "CYP 억제 → QT 간격 연장 + 에페드린 심장 자극 → 부정맥(TdP) 위험; 마황 간독성 + 항진균제 간독성 상가" },
  { id: "procaterol", koreanName: "프로카테롤염산염수화물", englishName: "Procaterol Hydrochloride", category: "기관지확장제/진해거담", status: "PROHIBITED", opinion: "교감신경계 상가 자극 → 심박수 증가, 저칼륨혈증, 부정맥 위험" },
  { id: "pseudoephedrine", koreanName: "슈도에페드린염산염", englishName: "Pseudoephedrine Hydrochloride", category: "코막힘/비충혈제거제", status: "PROHIBITED", opinion: "동일 기전 약물 중복 → 과도한 교감신경 자극, 고혈압 위기, 부정맥 위험" },
  { id: "salbutamol", koreanName: "살부타몰황산염", englishName: "Salbutamol Sulfate", category: "기관지확장제/천식발작", status: "PROHIBITED", opinion: "교감신경계 상가 자극 → 심박수 증가, 저칼륨혈증, 부정맥 위험" },
  { id: "sertraline", koreanName: "설트랄린염산염", englishName: "Sertraline Hydrochloride", category: "SSRI 항우울제/불안장애", status: "PROHIBITED", opinion: "세로토닌 재흡수 차단 + 에페드린 → 세로토닌 증후군 위험" },
  { id: "sumatriptan", koreanName: "수마트립탄숙신산염", englishName: "Sumatriptan Succinate", category: "편두통치료제", status: "PROHIBITED", opinion: "혈관수축 기전 + 에페드린 혈관수축 → 관상동맥 수축, 혈관 경련 위험" },
  { id: "tacrolimus", koreanName: "타크로리무스수화물", englishName: "Tacrolimus Hydrate", category: "면역억제제", status: "PROHIBITED", opinion: "신독성·고혈압 유발약 + 에페드린의 혈관수축·혈압상승 → 신독성·고혈압 악화" },
  { id: "tetrahydrozoline", koreanName: "테트라히드로졸린염산염", englishName: "Tetrahydrozoline Hydrochloride", category: "비충혈제거제/안약", status: "PROHIBITED", opinion: "동일 기전 약물 중복 → 과도한 교감신경 자극, 고혈압 위험" },
  { id: "theobromine", koreanName: "테오브로민", englishName: "Theobromine", category: "진해제/호흡기", status: "PROHIBITED", opinion: "PDE 억제 + 아데노신 길항 → 에페드린과 심장 자극 상가 위험" },
  { id: "theophylline", koreanName: "테오필린", englishName: "Theophylline", category: "천식/기관지확장제", status: "PROHIBITED", opinion: "PDE 억제 + 아데노신 길항 → 에페드린과 심장 자극 상가, 부정맥·경련 위험" },
  { id: "tramadol", koreanName: "트라마돌염산염", englishName: "Tramadol Hydrochloride", category: "중증진통제/마약성유사", status: "PROHIBITED", opinion: "세로토닌 증후군 + 경련 역치 저하 위험" },
  { id: "trazodone", koreanName: "트라조돈염산염", englishName: "Trazodone Hydrochloride", category: "항우울제/수면유도", status: "PROHIBITED", opinion: "세로토닌 조절 작용 + 에페드린 → 세로토닌 증후군 위험" },
  { id: "tulobuterol", koreanName: "툴로부테롤", englishName: "Tulobuterol", category: "기관지확장 패치제", status: "PROHIBITED", opinion: "교감신경계 상가 자극 → 심박수 증가, 저칼륨혈증, 부정맥 위험" },
  { id: "venlafaxine", koreanName: "벤라팍신염산염", englishName: "Venlafaxine Hydrochloride", category: "SNRI 항우울제", status: "PROHIBITED", opinion: "세로토닌·노르에피네프린 이중 차단 + 에페드린 → 세로토닌 증후군 + 고혈압 이중 위험" },
  { id: "vilanterol", koreanName: "빌란테롤트리페나테이트", englishName: "Vilanterol Trifenatate", category: "천식/COPD 흡입제", status: "PROHIBITED", opinion: "교감신경계 상가 자극 → 심박수 증가, 저칼륨혈증, 부정맥 위험" },
  { id: "voriconazole", koreanName: "보리코나졸", englishName: "Voriconazole", category: "항진균제", status: "PROHIBITED", opinion: "CYP 억제 → QT 간격 연장 + 에페드린 심장 자극 → 부정맥(TdP) 위험; 마황 간독성 + 항진균제 간독성 상가" },
  { id: "vortioxetine", koreanName: "보티옥세틴브롬화수소산염", englishName: "Vortioxetine Hydrobromide", category: "다중작용 항우울제", status: "PROHIBITED", opinion: "세로토닌 조절 + 에페드린 → 세로토닌 증후군 위험" },
  { id: "synthroid", koreanName: "신지로이드", englishName: "Synthroid", category: "갑상선호르몬제", status: "PROHIBITED", opinion: "갑상선 호르몬이 카테콜아민 감수성 증가 → 에페드린과 빈맥, 부정맥, 고혈압 위험 증폭" },
  { id: "phentermine", koreanName: "펜터민염산염", englishName: "Phentermine Hydrochloride", category: "양방 식욕억제제", status: "PROHIBITED", opinion: "교감신경 자극 및 노르에피네프린 분비 중복 → 극심한 두근거림, 불면, 급성 고혈압 위기 위험" },
  { id: "phendimetrazine", koreanName: "펜디메트라진타르타르산염", englishName: "Phendimetrazine Tartrate", category: "양방 식욕억제제", status: "PROHIBITED", opinion: "교감신경계 과다 흥분 중복 → 심계항진, 혈압 상승, 중추신경계 부작용 위험" },
  { id: "methylphenidate", koreanName: "메틸페니데이트염산염", englishName: "Methylphenidate Hydrochloride", category: "ADHD치료제", status: "PROHIBITED", opinion: "도파민·노르에피네프린 재흡수 억제로 에페드린과 교감신경 및 심혈관계 자극 상승" },

  // === [주의 필요 (CAUTION)] ===
  { id: "aceclofenac", koreanName: "아세클로페낙", englishName: "Aceclofenac", category: "소염진통제 (NSAIDs)", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 장기 복용 시 심혈관·신장 손상 누적 위험: 에페드린(혈관수축·혈압↑) + NSAID(COX 억제→신장 프로스타글란딘↓→신장관류↓) 이중 신장 손상; 지속성 고혈압으로 심혈관 부담" },
  { id: "acetaminophen", koreanName: "아세트아미노펜", englishName: "Acetaminophen", category: "해열진통제", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 마황의 CYP2E1 부하·산화 스트레스 + 아세트아미노펜 NAPQI 독성 증가 → 3개월 장기 복용 시 간손상 누적 위험 (음주자+아세트아미노펜 조합과 동일 기전)" },
  { id: "alprazolam", koreanName: "알프라졸람", englishName: "Alprazolam", category: "신경안정제/항불안제", status: "CAUTION", opinion: "GABA 수용체 작용(진정) vs 에페드린(각성) → 양방향 효과 감소; 위험한 약리 상호작용 아님" },
  { id: "amlodipine", koreanName: "암로디핀", englishName: "Amlodipine", category: "칼슘채널차단 혈압약(CCB)", status: "CAUTION", opinion: "에페드린이 혈압 상승시켜 항고혈압 효과 감소, 심부전 치료 시에는 병용 불가" },
  { id: "apixaban", koreanName: "아픽사반", englishName: "Apixaban", category: "항응고제(NOAC)", status: "CAUTION", opinion: "심혈관 질환자 확인 필요 → 혈전·출혈 고위험 환자에 혈압 상승 약물 금기" },
  { id: "aripiprazole", koreanName: "아리피프라졸", englishName: "Aripiprazole", category: "항정신병약/우울보조", status: "CAUTION", opinion: "도파민 수용체와 에페드린 간 카테콜아민 직접 증폭 효과 없음; 정신과 질환 치료 중 교감신경 흥분제 처방 임상적 적합성 우선 검토 필요" },
  { id: "aspirin", koreanName: "아스피린", englishName: "Aspirin", category: "소염진통/항혈전제", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 장기 복용 시 심혈관·신장 손상 누적 위험: 에페드린(혈관수축·혈압↑) + NSAID 이중 신장 손상" },
  { id: "baclofen", koreanName: "바클로펜", englishName: "Baclofen", category: "근이완제", status: "CAUTION", opinion: "중추신경계 억제 + 에페드린 자극 → 상호 효과 감소; 직접 위험은 낮음" },
  { id: "betamethasone", koreanName: "베타메타손", englishName: "Betamethasone", category: "스테로이드제", status: "CAUTION", opinion: "스테로이드의 체지방 증가·근육 분해로 다이어트 효과 방해; 직접 약물상호작용보다 치료 목적 상충" },
  { id: "budesonide", koreanName: "부데소니드", englishName: "Budesonide", category: "흡입 스테로이드", status: "CAUTION", opinion: "스테로이드의 체지방 증가·근육 분해로 다이어트 효과 방해; 직접 약물상호작용보다 치료 목적 상충" },
  { id: "candesartan", koreanName: "칸데사르탄", englishName: "Candesartan", category: "고혈압약(ARB)", status: "CAUTION", opinion: "에페드린이 혈압 상승시켜 항고혈압 효과 감소, 심부전 치료 시에는 병용 불가" },
  { id: "carvedilol", koreanName: "카르베딜롤", englishName: "Carvedilol", category: "베타차단 혈압약", status: "CAUTION", opinion: "에페드린이 항고혈압 효과 감소시킴" },
  { id: "celecoxib", koreanName: "셀레콕시브", englishName: "Celecoxib", category: "소염진통제 (COX-2 선택적)", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 장기 복용 시 심혈관·신장 손상 누적 위험, COX-2 선택적 억제제도 독립적 심혈관 위험 존재; 에페드린과 상가 심혈관 부담" },
  { id: "chlorpheniramine", koreanName: "클로르페니라민말레산염", englishName: "Chlorpheniramine Maleate", category: "1세대 항히스타민제", status: "CAUTION", opinion: "체중 증가 효과로 다이어트 효과 감소 | 에페드린과 항콜린 상가 작용 (빈맥, 구갈, 요폐 증폭)" },
  { id: "cilostazol", koreanName: "실로스타졸", englishName: "Cilostazol", category: "혈소판응집억제/말초순환개선", status: "CAUTION", opinion: "PDE3 억제 → 심박수 증가 + 에페드린 빈맥 → 부정맥 상가 위험; 심혈관 질환자에게 교감신경 흥분제 부적절" },
  { id: "clonazepam", koreanName: "클로나제팜", englishName: "Clonazepam", category: "항전간제/공황장애", status: "CAUTION", opinion: "GABA 수용체 작용(진정) vs 에페드린(각성) → 양방향 효과 감소; 위험한 약리 상호작용 아님" },
  { id: "clopidogrel", koreanName: "클로피도그렐황산수소염", englishName: "Clopidogrel Bisulfate", category: "항혈전제", status: "CAUTION", opinion: "심혈관 질환자 확인 필요 → 혈전·출혈 고위험 환자에 혈압 상승 약물 금기" },
  { id: "codeine", koreanName: "코데인", englishName: "Codeine", category: "진통·진해제", status: "CAUTION", opinion: "CNS 억제(진통·진해) vs 에페드린 각성 → 약효 상쇄; 직접 위험한 약리 상호작용 아님" },
  { id: "dexamethasone", koreanName: "덱사메타손", englishName: "Dexamethasone", category: "스테로이드제", status: "CAUTION", opinion: "스테로이드의 체지방 증가·근육 분해로 다이어트 효과 방해; 직접 약물상호작용보다 치료 목적 상충" },
  { id: "dexibuprofen", koreanName: "덱시부프로펜", englishName: "Dexibuprofen", category: "소염진통제 (NSAIDs)", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 장기 복용 시 심혈관·신장 손상 누적 위험: 에페드린(혈관수축·혈압↑) + NSAID 이중 신장 손상" },
  { id: "diazepam", koreanName: "디아제팜", englishName: "Diazepam", category: "신경안정제", status: "CAUTION", opinion: "GABA 수용체 작용(진정) vs 에페드린(각성) → 양방향 효과 감소; 위험한 약리 상호작용 아님" },
  { id: "diclofenac", koreanName: "디클로페낙", englishName: "Diclofenac", category: "소염진통제 (NSAIDs)", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 장기 복용 시 심혈관·신장 손상 누적 위험" },
  { id: "dihydrocodeine", koreanName: "디히드로코데인타르타르산염", englishName: "Dihydrocodeine Tartrate", category: "진해거담제 (처방약)", status: "CAUTION", opinion: "CNS 억제(진통·진해) vs 에페드린 각성 → 약효 상쇄, 직접 위험한 약리 상호작용 아님" },
  { id: "diltiazem", koreanName: "딜티아젬염산염", englishName: "Diltiazem Hydrochloride", category: "고혈압/부정맥약(CCB)", status: "CAUTION", opinion: "에페드린이 혈압 상승시켜 항고혈압 효과 감소, 심부전 치료 시에는 병용 불가" },
  { id: "domperidone", koreanName: "돔페리돈", englishName: "Domperidone", category: "위장운동촉진제", status: "CAUTION", opinion: "QT 연장 우려 + 에페드린 심장 자극 → 부정맥 주의" },
  { id: "edoxaban", koreanName: "에독사반", englishName: "Edoxaban", category: "항응고제(NOAC)", status: "CAUTION", opinion: "심혈관 질환자 확인 필요 → 혈전·출혈 고위험 환자에 혈압 상승 약물 금기" },
  { id: "empagliflozin", koreanName: "엠파글리플로진", englishName: "Empagliflozin", category: "당뇨병치료제(SGLT-2)", status: "CAUTION", opinion: "혈당 조절 상태 모니터링 필요" },
  { id: "esomeprazole", koreanName: "에스오메프라졸", englishName: "Esomeprazole", category: "위산분비억제제(PPI)", status: "CAUTION", opinion: "위산 분비 감소 → 에페드린 흡수 촉진, 약효·부작용 빠르게 나타날 수 있음" },
  { id: "fimasartan", koreanName: "피마사르탄칼륨", englishName: "Fimasartan Potassium", category: "고혈압약(ARB)", status: "CAUTION", opinion: "에페드린이 혈압 상승시켜 항고혈압 효과 감소, 심부전 치료 시에는 병용 불가" },
  { id: "fluticasone", koreanName: "플루티카손", englishName: "Fluticasone", category: "비염 스프레이/흡입스테로이드", status: "CAUTION", opinion: "스테로이드의 체지방 증가·근육 분해로 다이어트 효과 방해; 직접 약물상호작용보다 치료 목적 상충" },
  { id: "furosemide", koreanName: "푸로세미드", englishName: "Furosemide", category: "루프 이뇨제", status: "CAUTION", opinion: "에페드린이 이뇨 효과 감소시킬 수 있음; 직접 위험한 상호작용은 낮음" },
  { id: "glimepiride", koreanName: "글리메피리드", englishName: "Glimepiride", category: "당뇨병약", status: "CAUTION", opinion: "저혈당 위험 주의" },
  { id: "ibuprofen", koreanName: "이부프로펜", englishName: "Ibuprofen", category: "소염진통제 (NSAIDs)", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 장기 복용 시 심혈관·신장 손상 누적 위험: 에페드린(혈관수축·혈압↑) + NSAID 이중 신장 손상" },
  { id: "ketoprofen", koreanName: "케토프로펜", englishName: "Ketoprofen", category: "소염진통제/관절염약", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 장기 복용 시 심혈관·신장 손상 누적 위험" },
  { id: "lorazepam", koreanName: "로라제팜", englishName: "Lorazepam", category: "신경안정제/항불안제", status: "CAUTION", opinion: "GABA 수용체 작용(진정) vs 에페드린(각성) → 양방향 효과 감소; 위험한 약리 상호작용 아님" },
  { id: "losartan", koreanName: "로사르탄칼륨", englishName: "Losartan Potassium", category: "고혈압약(ARB)", status: "CAUTION", opinion: "에페드린이 혈압 상승시켜 항고혈압 효과 감소, 심부전 치료 시에는 병용 불가" },
  { id: "loxoprofen", koreanName: "록소프로펜나트륨수화물", englishName: "Loxoprofen Sodium Hydrate", category: "소염진통제 (NSAIDs)", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 장기 복용 시 심혈관·신장 손상 누적 위험: 에페드린(혈관수축·혈압↑) + NSAID 이중 신장 손상" },
  { id: "meloxicam", koreanName: "멜록시캄", englishName: "Meloxicam", category: "소염진통제 (관절염 처방약)", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 장기 복용 시 심혈관·신장 손상 누적 위험, COX-2 선택적 억제제도 독립적 심혈관 위험 존재" },
  { id: "methylprednisolone", koreanName: "메틸프레드니솔론", englishName: "Methylprednisolone", category: "스테로이드제", status: "CAUTION", opinion: "스테로이드의 체지방 증가·근육 분해로 다이어트 효과 방해; 직접 약물상호작용보다 치료 목적 상충" },
  { id: "minoxidil", koreanName: "미녹시딜", englishName: "Minoxidil", category: "탈모치료/혈압약", status: "CAUTION", opinion: "탈모 목적: 병용 가능 / 고혈압 치료 목적: 병용 주의" },
  { id: "mosapride", koreanName: "모사프리드시트르산염수화물", englishName: "Mosapride Citrate", category: "위장관운동촉진제", status: "CAUTION", opinion: "세로토닌 수용체 작용 → 중추신경계 영향, 에페드린 부작용 강화 가능성" },
  { id: "naproxen", koreanName: "나프록센", englishName: "Naproxen", category: "소염진통제 (NSAIDs)", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 장기 복용 시 심혈관·신장 손상 누적 위험: 에페드린(혈관수축·혈압↑) + NSAID(COX 억제→신장 프로스타글란딘↓→신장관류↓) 이중 신장 손상; 지속성 고혈압으로 심혈관 부담" },
  { id: "pelubiprofen", koreanName: "펠루비프로펜", englishName: "Pelubiprofen", category: "소염진통제 (NSAIDs)", status: "CAUTION", opinion: "복용 시 다이어트환은 중단. 장기 복용 시 심혈관·신장 손상 누적 위험" },
  { id: "prednisolone", koreanName: "프레드니솔론", englishName: "Prednisolone", category: "스테로이드제", status: "CAUTION", opinion: "스테로이드의 체지방 증가·근육 분해로 다이어트 효과 방해; 직접 약물상호작용보다 치료 목적 상충" },
  { id: "pregabalin", koreanName: "프레가발린", englishName: "Pregabalin", category: "신경병증성 통증/뇌전증", status: "CAUTION", opinion: "뇌전증 치료 중: 처방 불가 / 통증 치료 중: 복용 종료 후 처방 가능" },
  { id: "propranolol", koreanName: "프로프라놀롤염산염", englishName: "Propranolol Hydrochloride", category: "비선택적 베타차단제/면접떨림약", status: "CAUTION", opinion: "에페드린과 병용 시 비길항 알파 자극 가능 → 고혈압 위험; 항고혈압 효과 감소" },
  { id: "rabeprazole", koreanName: "라베프라졸나트륨", englishName: "Rabeprazole Sodium", category: "위산분비억제제(PPI)", status: "CAUTION", opinion: "위산 분비 감소 → 에페드린 흡수 촉진 가능" },
  { id: "rivaroxaban", koreanName: "리바록사반", englishName: "Rivaroxaban", category: "항응고제(NOAC)", status: "CAUTION", opinion: "심혈관 질환자 확인 필요 → 혈전·출혈 고위험 환자에 혈압 상승 약물 금기" },
  { id: "tegoprazan", koreanName: "테고프라잔", englishName: "Tegoprazan", category: "위식도역류치료제(P-CAB)", status: "CAUTION", opinion: "위산 분비 감소 → 에페드린 흡수 촉진 가능" },
  { id: "telmisartan", koreanName: "텔미사르탄", englishName: "Telmisartan", category: "고혈압약(ARB)", status: "CAUTION", opinion: "에페드린이 혈압 상승시켜 항고혈압 효과 감소, 심부전 치료 시에는 병용 불가" },
  { id: "triamcinolone", koreanName: "트리암시놀론", englishName: "Triamcinolone", category: "스테로이드제", status: "CAUTION", opinion: "스테로이드의 체지방 증가·근육 분해로 다이어트 효과 방해; 직접 약물상호작용보다 치료 목적 상충" },
  { id: "ursodeoxycholic_acid", koreanName: "우르소데옥시콜산 (UDCA)", englishName: "Ursodeoxycholic Acid", category: "간장약/담즙분비촉진", status: "CAUTION", opinion: "간질환 치료 중일 가능성 고려; 간질환 없는 경우 병용 가능" },
  { id: "valsartan", koreanName: "발사르탄", englishName: "Valsartan", category: "고혈압약(ARB)", status: "CAUTION", opinion: "에페드린이 혈압 상승시켜 항고혈압 효과 감소, 심부전 치료 시에는 병용 불가" },
  { id: "warfarin", koreanName: "와파린", englishName: "Warfarin Sodium", category: "항응고제", status: "CAUTION", opinion: "심혈관 질환자 확인 필요 → 혈전·출혈 고위험 환자에 혈압 상승 약물 금기; 에페드린에 의한 혈압 상승 주의" },
  { id: "zolpidem", koreanName: "졸피뎀타르타르산염", englishName: "Zolpidem Tartrate", category: "수면제", status: "CAUTION", opinion: "진정·수면 촉진 vs 에페드린 각성·불면 유발 → 상반 작용, 양방향 효과 감소" },

  // === [안전 (SAFE) 다빈도 성분] ===
  { id: "erdosteine", koreanName: "에르도스테인", englishName: "Erdosteine", category: "진해거담제 (처방약)", status: "SAFE", opinion: "에페드린과의 심혈관계 및 중추신경계 상호작용이 없어 안전하게 병용 가능합니다." },
  { id: "acetylcysteine", koreanName: "아세틸시스테인", englishName: "Acetylcysteine", category: "진해거담제", status: "SAFE", opinion: "호흡기 점액 용해제로 다이어트 한약과 안전하게 병용 가능합니다." },
  { id: "ambroxol", koreanName: "암브록솔염산염", englishName: "Ambroxol Hydrochloride", category: "진해거담제", status: "SAFE", opinion: "기관지 분비 촉진제로 다이어트 한약과 안전하게 병용 가능합니다." },
  { id: "levodropropizine", koreanName: "레보드로프로피진", englishName: "Levodropropizine", category: "진해제 (처방약)", status: "SAFE", opinion: "말초성 진해제로 중추신경계 자극이 없어 안전하게 병용 가능합니다." },
  { id: "cetirizine", koreanName: "세티리진염산염", englishName: "Cetirizine Hydrochloride", category: "2세대 항히스타민제", status: "SAFE", opinion: "슈도에페드린이 포함되지 않은 순수 항히스타민 단일제는 복용 가능합니다." },
  { id: "levocetirizine", koreanName: "레보세티리진염산염", englishName: "Levocetirizine Hydrochloride", category: "3세대 항히스타민제", status: "SAFE", opinion: "졸음과 심혈관 부작용이 적은 안전한 항히스타민제입니다." },
  { id: "fexofenadine", koreanName: "펙소페나딘염산염", englishName: "Fexofenadine Hydrochloride", category: "3세대 항히스타민제", status: "SAFE", opinion: "다이어트 한약과 상호작용이 없는 안전한 비염/알레르기 치료제입니다." },
  { id: "loratadine", koreanName: "로라타딘", englishName: "Loratadine", category: "2세대 항히스타민제", status: "SAFE", opinion: "다이어트 한약과 병용 가능한 안전한 항히스타민제입니다." },
  { id: "ebastine", koreanName: "에바스틴", englishName: "Ebastine", category: "2세대 항히스타민제", status: "SAFE", opinion: "다이어트 한약과 안전하게 병용 가능한 항히스타민제입니다." },
  { id: "magnesium_oxide", koreanName: "산화마그네슘", englishName: "Magnesium Oxide", category: "변비완화제/제산제", status: "SAFE", opinion: "다이어트 한약 복용 중 변비 시 안전하게 병용 복용 가능합니다." },
  { id: "rebamipide", koreanName: "레바미피드", englishName: "Rebamipide", category: "위점막보호제 (처방약)", status: "SAFE", opinion: "위점막 보호제로 다이어트 한약과 안전하게 병용 가능합니다." },
  { id: "almagate", koreanName: "알마게이트", englishName: "Almagate", category: "제산제", status: "SAFE", opinion: "위산 중화제로 다이어트 한약 복용 시 속쓰림 완화에 병용 가능합니다." },
  { id: "famotidine", koreanName: "파모티딘", englishName: "Famotidine", category: "위장약 (H2차단제)", status: "SAFE", opinion: "위산분비 억제제로 다이어트 한약과 안전하게 복용 가능합니다." },
  { id: "trimebutine", koreanName: "트리메부틴말레산염", englishName: "Trimebutine Maleate", category: "위장관운동조절제", status: "SAFE", opinion: "위장관 운동 정상화제로 복통, 소화불량 시 안전하게 병용 가능합니다." },
  { id: "artemisia_extract", koreanName: "애엽에탄올추출물", englishName: "Artemisia Extract", category: "위염치료제 (스티렌 등)", status: "SAFE", opinion: "천연물 유래 위염치료제로 다이어트 한약과 안전하게 병용 가능합니다." }
];

// 2. 국내 다빈도 의약품(상표명) 대규모 전수 매핑 데이터셋 (150+ 핵심 품목)
const POPULAR_COMMERCIAL_DRUGS = [
  // --- 소염진통제 (탁센, 타이레놀, 이지엔6, 낙센, 록소닌, 에어탈, 쎄레브렉스 등) ---
  { id: "taxen", brandName: "탁센연질캡슐", company: "GC녹십자", category: "소염진통제 (나프록센)", ingredients: [{ name: "나프록센", amount: "250mg" }] },
  { id: "taxen_eve", brandName: "탁센이브연질캡슐", company: "GC녹십자", category: "생리통 진통제", ingredients: [{ name: "이부프로펜", amount: "200mg" }, { name: "파마브롬", amount: "25mg" }] },
  { id: "taxen_lady", brandName: "탁센레이디연질캡슐", company: "GC녹십자", category: "생리통 진통제", ingredients: [{ name: "이부프로펜", amount: "200mg" }, { name: "파마브롬", amount: "25mg" }] },
  { id: "taxen_dexi", brandName: "탁센덱시연질캡슐", company: "GC녹십자", category: "소염진통제", ingredients: [{ name: "덱시부프로펜", amount: "300mg" }] },
  { id: "taxen_400", brandName: "탁센400이부프로펜", company: "GC녹십자", category: "소염진통제", ingredients: [{ name: "이부프로펜", amount: "400mg" }] },
  { id: "tylenol_500", brandName: "타이레놀정 500mg", company: "한국존슨앤드존슨", category: "해열진통제", ingredients: [{ name: "아세트아미노펜", amount: "500mg" }] },
  { id: "tylenol_er", brandName: "타이레놀 8시간 이알 서방정", company: "한국존슨앤드존슨", category: "서방형 해열진통제", ingredients: [{ name: "아세트아미노펜", amount: "650mg" }] },
  { id: "tacenol", brandName: "타세놀정 500mg / 타세놀이알", company: "대웅제약", category: "해열진통제", ingredients: [{ name: "아세트아미노펜", amount: "500~650mg" }] },
  { id: "setopen", brandName: "세토펜정 / 세토펜현탁액", company: "삼아제약", category: "해열진통제 (처방약)", ingredients: [{ name: "아세트아미노펜", amount: "325~500mg" }] },
  { id: "suspen", brandName: "써스펜이알서방정", company: "한미약품", category: "해열진통제", ingredients: [{ name: "아세트아미노펜", amount: "650mg" }] },
  { id: "ezn6_ani", brandName: "이지엔6애니연질캡슐", company: "대웅제약", category: "소염진통제", ingredients: [{ name: "이부프로펜", amount: "200mg" }] },
  { id: "ezn6_pro", brandName: "이지엔6프로연질캡슐", company: "대웅제약", category: "소염진통제", ingredients: [{ name: "덱시부프로펜", amount: "300mg" }] },
  { id: "ezn6_eve", brandName: "이지엔6이브연질캡슐", company: "대웅제약", category: "생리통 진통제", ingredients: [{ name: "이부프로펜", amount: "200mg" }, { name: "파마브롬", amount: "25mg" }] },
  { id: "ezn6_ace", brandName: "이지엔6에이스", company: "대웅제약", category: "해열진통제", ingredients: [{ name: "아세트아미노펜", amount: "325mg" }] },
  { id: "ezn6_strong", brandName: "이지엔6스트롱연질캡슐", company: "대웅제약", category: "소염진통제", ingredients: [{ name: "나프록센", amount: "250mg" }] },
  { id: "advil", brandName: "애드빌정 / 애드빌리퀴겔", company: "GSK", category: "소염진통제", ingredients: [{ name: "이부프로펜", amount: "200mg" }] },
  { id: "naxen", brandName: "낙센정 / 낙센에프", company: "종근당", category: "소염진통제", ingredients: [{ name: "나프록센", amount: "250~500mg" }] },
  { id: "loxonin", brandName: "록소닌정 / 록스펜정", company: "동화약품", category: "소염진통제 (처방약)", ingredients: [{ name: "록소프로펜나트륨수화물", amount: "68.1mg" }] },
  { id: "airtal", brandName: "에어탈정 / 아세클로정", company: "대웅제약", category: "소염진통제 (처방약)", ingredients: [{ name: "아세클로페낙", amount: "100mg" }] },
  { id: "celebrex", brandName: "쎄레브렉스캡슐 (100mg / 200mg)", company: "한국비아트리스", category: "소염진통제 (처방약)", ingredients: [{ name: "셀레콕시브", amount: "100~200mg" }] },
  { id: "pelubi", brandName: "펠루비정 / 펠루비서방정", company: "대원제약", category: "소염진통제 (처방약)", ingredients: [{ name: "펠루비프로펜", amount: "30~45mg" }] },
  { id: "mobic", brandName: "모빅캡슐 (7.5mg / 15mg)", company: "한국베링거", category: "소염진통제 (처방약)", ingredients: [{ name: "멜록시캄", amount: "7.5~15mg" }] },
  { id: "soleton", brandName: "솔레톤정 (80mg)", company: "CJ헬스케어/HK이노엔", category: "소염진통제 (처방약)", ingredients: [{ name: "잘토프로펜", amount: "80mg" }] },
  { id: "pontal", brandName: "폰탈캡슐 (250mg / 500mg)", company: "유한양행", category: "소염진통제", ingredients: [{ name: "메페남산", amount: "250~500mg" }] },
  { id: "aspirin_protect", brandName: "아스피린프로텍트정 100mg", company: "바이엘", category: "항혈전/소염진통", ingredients: [{ name: "아스피린", amount: "100mg" }] },
  { id: "geborin", brandName: "게보린정", company: "삼진제약", category: "복합진통제", ingredients: [{ name: "아세트아미노펜", amount: "300mg" }, { name: "카페인무수물", amount: "50mg" }] },
  { id: "penzal_q", brandName: "펜잘큐정", company: "종근당", category: "복합진통제", ingredients: [{ name: "아세트아미노펜", amount: "300mg" }, { name: "카페인무수물", amount: "50mg" }] },
  { id: "gralen", brandName: "그날엔정", company: "경동제약", category: "복합진통제", ingredients: [{ name: "이부프로펜", amount: "75mg" }, { name: "카페인무수물", amount: "40mg" }] },
  { id: "ultracet", brandName: "울트라셋정 / 울트라셋이알 / 파라마셋", company: "한국얀센", category: "중증진통제 (처방약)", ingredients: [{ name: "트라마돌염산염", amount: "37.5mg" }, { name: "아세트아미노펜", amount: "325mg" }] },

  // --- 호흡기 / 감기약 / 진해거담제 / 비염약 ---
  { id: "pancol_a", brandName: "판콜에이내복액", company: "동화약품", category: "종합감기약 (액상)", ingredients: [{ name: "DL-메틸에페드린염산염", amount: "17.5mg" }, { name: "카페인무수물", amount: "30mg" }, { name: "아세트아미노펜", amount: "300mg" }] },
  { id: "pancol_s", brandName: "판콜에스내복액", company: "동화약품", category: "종합감기약 (액상)", ingredients: [{ name: "DL-메틸에페드린염산염", amount: "17.5mg" }, { name: "카페인무수물", amount: "30mg" }, { name: "아세트아미노펜", amount: "300mg" }] },
  { id: "panpyrin_q", brandName: "판피린큐액 / 판피린티", company: "동아제약", category: "종합감기약", ingredients: [{ name: "DL-메틸에페드린염산염", amount: "10mg" }, { name: "카페인무수물", amount: "30mg" }, { name: "아세트아미노펜", amount: "300mg" }] },
  { id: "theraflu_night", brandName: "테라플루나이트타임건조시럽", company: "GSK", category: "종합감기약", ingredients: [{ name: "페닐레프린염산염", amount: "10mg" }, { name: "아세트아미노펜", amount: "650mg" }] },
  { id: "theraflu_day", brandName: "테라플루데이타임건조시럽", company: "GSK", category: "종합감기약", ingredients: [{ name: "페닐레프린염산염", amount: "10mg" }, { name: "아세트아미노펜", amount: "650mg" }] },
  { id: "codaewon_forte", brandName: "코대원포르테시럽", company: "대원제약", category: "진해거담제 (처방약)", ingredients: [{ name: "DL-메틸에페드린염산염", amount: "1.31mg/mL" }, { name: "디히드로코데인타르타르산염", amount: "0.5mg/mL" }] },
  { id: "cofu_syrup", brandName: "코푸시럽 / 코푸정", company: "유한양행", category: "진해거담제 (처방약)", ingredients: [{ name: "DL-메틸에페드린염산염", amount: "1.31mg/mL" }, { name: "디히드로코데인타르타르산염", amount: "0.5mg/mL" }] },
  { id: "codaewon_s", brandName: "코대원에스시럽", company: "대원제약", category: "진해거담제 (처방약)", ingredients: [{ name: "DL-메틸에페드린염산염", amount: "1.31mg/mL" }, { name: "펠라고니움추출물" }] },
  { id: "mucopect", brandName: "뮤코펙트정 / 뮤코펙트시럽", company: "사노피", category: "진해거담제", ingredients: [{ name: "암브록솔염산염", amount: "30mg" }] },
  { id: "eldos", brandName: "엘도스캡슐 / 에르도스", company: "대웅제약", category: "진해거담제 (처방약)", ingredients: [{ name: "에르도스테인", amount: "300mg" }] },
  { id: "levotuss", brandName: "레보투스시럽 / 레보드로피진", company: "현대약품", category: "진해제 (처방약)", ingredients: [{ name: "레보드로프로피진", amount: "60mg" }] },
  { id: "synatura", brandName: "시네츄라시럽", company: "안국약품", category: "진해거담제 (처방약)", ingredients: [{ name: "아이비엽추출물", amount: "다양" }, { name: "황련추출물" }] },
  { id: "sudafed", brandName: "슈다페드정 (60mg)", company: "삼일제약", category: "비염/코막힘약", ingredients: [{ name: "슈도에페드린염산염", amount: "60mg" }] },
  { id: "actifed", brandName: "액티피드정", company: "삼일제약", category: "코감기/비염약", ingredients: [{ name: "슈도에페드린염산염", amount: "60mg" }, { name: "트리프롤리딘염산염", amount: "2.5mg" }] },
  { id: "zyrtec", brandName: "지르텍정 (10mg)", company: "한국유씨비", category: "알레르기/비염약", ingredients: [{ name: "세티리진염산염", amount: "10mg" }] },
  { id: "allegra", brandName: "알레그라정 (120mg / 180mg)", company: "사노피", category: "알레르기/비염약", ingredients: [{ name: "펙소페나딘염산염", amount: "120~180mg" }] },
  { id: "xyzal", brandName: "씨잘정 (5mg) / 씨잘액", company: "한국유씨비", category: "알레르기/비염약 (처방약)", ingredients: [{ name: "레보세티리진염산염", amount: "5mg" }] },
  { id: "claritin", brandName: "클라리틴정 (10mg)", company: "바이엘", category: "알레르기/비염약", ingredients: [{ name: "로라타딘", amount: "10mg" }] },
  { id: "ebastel", brandName: "에바스텔정 (10mg)", company: "보령", category: "알레르기/비염약 (처방약)", ingredients: [{ name: "에바스틴", amount: "10mg" }] },
  { id: "singulair", brandName: "싱귤레어정 (10mg) / 몬테락", company: "한국MSD", category: "천식/비염치료제", ingredients: [{ name: "몬테루카스트나트륨", amount: "10mg" }] },
  { id: "hocunalin", brandName: "호쿠날린패치 (0.5mg / 1mg / 2mg)", company: "한독", category: "기관지확장 패치제", ingredients: [{ name: "툴로부테롤", amount: "0.5~2mg" }] },
  { id: "ventolin", brandName: "벤토린에어로솔 / 벤토린정", company: "GSK", category: "기관지확장제", ingredients: [{ name: "살부타몰황산염", amount: "100mcg" }] },
  { id: "symbicort", brandName: "심비코트터부헬러", company: "아스트라제네카", category: "천식 흡입제", ingredients: [{ name: "포르모테롤", amount: "4.5mcg" }, { name: "부데소니드", amount: "160mcg" }] },

  // --- 위장약 / 소화기계 (케이캡, 넥시움, 스티렌, 알마겔, 가스모틴, 파모티딘, 포리부틴 등) ---
  { id: "k_cab", brandName: "케이캡정 (50mg / 구강붕해정)", company: "HK이노엔", category: "위식도역류약(P-CAB)", ingredients: [{ name: "테고프라잔", amount: "50mg" }] },
  { id: "nexium", brandName: "넥시움정 (20mg / 40mg)", company: "아스트라제네카", category: "위산분비억제제(PPI)", ingredients: [{ name: "에스오메프라졸", amount: "20~40mg" }] },
  { id: "esomezole", brandName: "에소메졸캡슐 / 에소메졸디알", company: "한미약품", category: "위산분비억제제(PPI)", ingredients: [{ name: "에스오메프라졸", amount: "20~40mg" }] },
  { id: "pariet", brandName: "파리에트정 (10mg / 20mg)", company: "한국에자이", category: "위산분비억제제(PPI)", ingredients: [{ name: "라베프라졸나트륨", amount: "10~20mg" }] },
  { id: "gasmotin", brandName: "가스모틴정 (5mg) / 모사원정", company: "대웅제약", category: "위장관운동촉진제 (처방약)", ingredients: [{ name: "모사프리드시트르산염수화물", amount: "5mg" }] },
  { id: "ganaton", brandName: "가나톤정 (50mg) / 이토메드", company: "JW중외제약", category: "위장관운동조절제", ingredients: [{ name: "이토프리드염산염", amount: "50mg" }] },
  { id: "stilrex", brandName: "스티렌정 / 스티렌투엑스", company: "동아ST", category: "위염치료제 (처방약)", ingredients: [{ name: "애엽에탄올추출물", amount: "60~90mg" }] },
  { id: "mucosta", brandName: "무코스타정 (100mg) / 레바미피드", company: "한국오츠카", category: "위점막보호제 (처방약)", ingredients: [{ name: "레바미피드", amount: "100mg" }] },
  { id: "almagel", brandName: "알마겔정 / 알마겔현탁액", company: "유한양행", category: "제산제", ingredients: [{ name: "알마게이트", amount: "500~1000mg" }] },
  { id: "gaviscon", brandName: "개비스콘더블액션현탁액", company: "옥시", category: "제산제", ingredients: [{ name: "알긴산나트륨", amount: "500mg" }] },
  { id: "famotidine_brand", brandName: "파모티딘정 (20mg) / 가스터정", company: "동아에스티/다양", category: "위장약 (H2차단제)", ingredients: [{ name: "파모티딘", amount: "20mg" }] },
  { id: "polybutin", brandName: "포리부틴정 (100mg / 150mg / 300mg)", company: "삼일제약", category: "위장관운동조절제", ingredients: [{ name: "트리메부틴말레산염", amount: "100~300mg" }] },
  { id: "magmil", brandName: "마그밀정 (500mg)", company: "삼남제약", category: "변비완화제/제산제", ingredients: [{ name: "산화마그네슘", amount: "500mg" }] },
  { id: "urusa", brandName: "우루사정 / 대웅우루사 (100mg / 200mg)", company: "대웅제약", category: "간장약/담즙개선", ingredients: [{ name: "우르소데옥시콜산", amount: "100~200mg" }] },
  { id: "festal", brandName: "훼스탈플러스정 / 훼스탈골드", company: "한독", category: "소화제", ingredients: [{ name: "판크레아틴", amount: "315mg" }] },
  { id: "bearse", brandName: "베아제정 / 닥터베아제", company: "대웅제약", category: "소화제", ingredients: [{ name: "판크레아틴", amount: "다양" }] },

  // --- 정신신경 / 수면제 / 갑상선 / 뇌전증 (씬지로이드, 스틸녹스, 자낙스, 리리카, 콘서타, 렉사프로 등) ---
  { id: "synthroid_brand", brandName: "씬지로이드정 (0.05mg / 0.1mg / 0.075mg)", company: "부광약품", category: "갑상선호르몬제", ingredients: [{ name: "레보티록신나트륨수화물", amount: "50~100mcg" }] },
  { id: "synthyroxin", brandName: "씬지록신정", company: "다림바이오텍", category: "갑상선호르몬제", ingredients: [{ name: "레보티록신나트륨수화물", amount: "50~100mcg" }] },
  { id: "stilnox", brandName: "스틸녹스정 (10mg / CR 12.5mg)", company: "한독", category: "수면제 (처방약)", ingredients: [{ name: "졸피뎀타르타르산염", amount: "10mg" }] },
  { id: "zolpid", brandName: "졸피드정 / 졸피뎀정", company: "한미약품", category: "수면제 (처방약)", ingredients: [{ name: "졸피뎀타르타르산염", amount: "10mg" }] },
  { id: "halcion", brandName: "할시온정 (0.125mg / 0.25mg)", company: "한국화이자", category: "수면진정제", ingredients: [{ name: "트리아졸람", amount: "0.25mg" }] },
  { id: "zanax", brandName: "자낙스정 (0.25mg / 0.5mg)", company: "한국화이자", category: "항불안제/신경안정", ingredients: [{ name: "알프라졸람", amount: "0.25~0.5mg" }] },
  { id: "ativan", brandName: "아티반정 (0.5mg / 1mg)", company: "일동제약", category: "항불안제/신경안정", ingredients: [{ name: "로라제팜", amount: "0.5~1mg" }] },
  { id: "valium", brandName: "바륨정 (2mg / 5mg)", company: "한국로슈", category: "신경안정제", ingredients: [{ name: "디아제팜", amount: "2~5mg" }] },
  { id: "rivotril", brandName: "리보트릴정 (0.5mg)", company: "한국로슈", category: "항전간제/공황장애", ingredients: [{ name: "클로나제팜", amount: "0.5mg" }] },
  { id: "lyrica", brandName: "리리카캡슐 (75mg / 150mg)", company: "한국화이자", category: "신경병증성 통증 (처방약)", ingredients: [{ name: "프레가발린", amount: "75~150mg" }] },
  { id: "neurontin", brandName: "뉴론틴캡슐 (100mg / 300mg)", company: "한국화이자", category: "신경통/항전간제", ingredients: [{ name: "가바펜틴", amount: "300mg" }] },
  { id: "indnol", brandName: "인데놀정 (10mg / 40mg)", company: "동광제약", category: "베타차단제/면접떨림", ingredients: [{ name: "프로프라놀롤염산염", amount: "10~40mg" }] },
  { id: "concerta", brandName: "콘서타OROS서방정 (18mg / 27mg / 36mg / 54mg)", company: "한국얀센", category: "ADHD 치료제", ingredients: [{ name: "메틸페니데이트염산염", amount: "18~54mg" }] },
  { id: "lexapro", brandName: "렉사프로정 (5mg / 10mg / 20mg)", company: "한국룬드벡", category: "SSRI 항우울제", ingredients: [{ name: "에스시탈로프람옥살산염", amount: "5~20mg" }] },
  { id: "prozac", brandName: "푸로작캡슐 (20mg)", company: "한국릴리", category: "SSRI 항우울제", ingredients: [{ name: "플루옥세틴염산염", amount: "20mg" }] },
  { id: "zoloft", brandName: "졸로푸트정 (50mg / 100mg)", company: "한국비아트리스", category: "SSRI 항우울제", ingredients: [{ name: "설트랄린염산염", amount: "50mg" }] },
  { id: "cymbalta", brandName: "심발타캡슐 (30mg / 60mg)", company: "한국릴리", category: "SNRI 항우울제/신경통", ingredients: [{ name: "둘록세틴염산염", amount: "30~60mg" }] },
  { id: "paxil_cr", brandName: "팍실CR정 (12.5mg / 25mg)", company: "GSK", category: "SSRI 항우울제", ingredients: [{ name: "파록세틴염산염수화물", amount: "12.5~25mg" }] },
  { id: "effexor", brandName: "이팩사XR서방캡슐", company: "한국비아트리스", category: "SNRI 항우울제", ingredients: [{ name: "벤라팍신염산염", amount: "37.5~75mg" }] },
  { id: "enafon", brandName: "에나폰정 (10mg / 25mg)", company: "하나제약", category: "TCA 항우울제/신경통", ingredients: [{ name: "아미트리프틸린염산염", amount: "10mg" }] },
  { id: "wellbutrin", brandName: "웰부트린서방정 (150mg)", company: "GSK", category: "항우울제/금연치료", ingredients: [{ name: "부프로피온염산염", amount: "150mg" }] },
  { id: "trittico", brandName: "트리티코정 (25mg / 50mg)", company: "국제약품", category: "항우울/수면진정", ingredients: [{ name: "트라조돈염산염", amount: "25~50mg" }] },
  { id: "remeron", brandName: "레메론정 (15mg / 30mg)", company: "한국MSD", category: "항우울제", ingredients: [{ name: "미르타자핀", amount: "15~30mg" }] },
  { id: "abilify", brandName: "아빌리파이정 (2mg / 5mg / 10mg)", company: "한국오츠카", category: "항정신병/우울보조", ingredients: [{ name: "아리피프라졸", amount: "2~10mg" }] },

  // --- 비만치료제 / 식욕억제제 (디에타민, 삭센다, 위고비, 콘트라브, 큐시미아, 제니칼 등) ---
  { id: "dietamin", brandName: "디에타민정 (나비약)", company: "대웅제약", category: "양방 식욕억제제", ingredients: [{ name: "펜터민염산염", amount: "37.5mg" }] },
  { id: "adipex", brandName: "아디펙스정", company: "광동제약", category: "양방 식욕억제제", ingredients: [{ name: "펜터민염산염", amount: "37.5mg" }] },
  { id: "puring", brandName: "푸링정", company: "알보젠코리아", category: "양방 식욕억제제", ingredients: [{ name: "펜디메트라진타르타르산염", amount: "35mg" }] },
  { id: "qsymia", brandName: "큐시미아캡슐", company: "알보젠코리아", category: "비만치료제 (복합제)", ingredients: [{ name: "펜터민염산염", amount: "3.75~15mg" }, { name: "토피라메이트", amount: "23~92mg" }] },
  { id: "contravez", brandName: "콘트라브서방정", company: "광동제약", category: "비만치료제", ingredients: [{ name: "부프로피온염산염", amount: "90mg" }, { name: "날트렉손염산염", amount: "8mg" }] },
  { id: "saxenda", brandName: "삭센다펜주 (6mg/mL)", company: "노보노디스크", category: "GLP-1 식욕억제 주사제", ingredients: [{ name: "리라글루티드", amount: "6mg/mL" }] },
  { id: "wegovy", brandName: "위고비펜주", company: "노보노디스크", category: "GLP-1 식욕억제 주사제", ingredients: [{ name: "세마글루티드", amount: "다양" }] },
  { id: "xenical", brandName: "제니칼캡슐 (120mg)", company: "종근당", category: "지방흡수억제제", ingredients: [{ name: "오르리스타트", amount: "120mg" }] },

  // --- 피부과 / 스테로이드 / 안과 / 항진균제 ---
  { id: "solondo", brandName: "소론도정 (5mg)", company: "유한양행", category: "부신피질호르몬/스테로이드", ingredients: [{ name: "프레드니솔론", amount: "5mg" }] },
  { id: "medrol", brandName: "메드롤정 (4mg)", company: "한국화이자", category: "부신피질호르몬/스테로이드", ingredients: [{ name: "메틸프레드니솔론", amount: "4mg" }] },
  { id: "oramedy", brandName: "오라메디연고", company: "동국제약", category: "구내염 연고", ingredients: [{ name: "트리암시놀론", amount: "1mg/g" }] },
  { id: "diflucan", brandName: "디푸루칸캡슐 (50mg / 150mg)", company: "한국화이자", category: "항진균제 (질염/무좀)", ingredients: [{ name: "플루코나졸", amount: "50~150mg" }] },
  { id: "sporanox", brandName: "스포라녹스캡슐", company: "한국얀센", category: "항진균제 (손발톱무좀)", ingredients: [{ name: "이트라코나졸", amount: "100mg" }] },

  // --- 순환기 / 고혈압 / 당뇨 / 항응고제 (노바스크, 카나브, 코자, 자디앙 등) ---
  { id: "norvasc", brandName: "노바스크정 (5mg / 10mg)", company: "한국비아트리스", category: "고혈압약(CCB)", ingredients: [{ name: "암로디핀", amount: "5~10mg" }] },
  { id: "kanarb", brandName: "카나브정 (60mg / 120mg)", company: "보령", category: "고혈압약(ARB)", ingredients: [{ name: "피마사르탄칼륨", amount: "60~120mg" }] },
  { id: "cozaar", brandName: "코자정 (50mg / 100mg)", company: "한국MSD", category: "고혈압약(ARB)", ingredients: [{ name: "로사르탄칼륨", amount: "50~100mg" }] },
  { id: "micardis", brandName: "미카르디스정 (40mg / 80mg)", company: "한국베링거", category: "고혈압약(ARB)", ingredients: [{ name: "텔미사르탄", amount: "40~80mg" }] },
  { id: "diovan", brandName: "디오반정 (80mg / 160mg)", company: "한국노바티스", category: "고혈압약(ARB)", ingredients: [{ name: "발사르탄", amount: "80~160mg" }] },
  { id: "jardiance", brandName: "자디앙정 (10mg / 25mg)", company: "한국베링거", category: "당뇨병약(SGLT-2)", ingredients: [{ name: "엠파글리플로진", amount: "10~25mg" }] },
  { id: "amaryl", brandName: "아마릴정 (1mg / 2mg / 4mg)", company: "한독", category: "당뇨병약", ingredients: [{ name: "글리메피리드", amount: "1~4mg" }] },
  { id: "plavix", brandName: "플라빅스정 75mg", company: "사노피", category: "항혈소판제", ingredients: [{ name: "클로피도그렐황산수소염", amount: "75mg" }] },
  { id: "xarelto", brandName: "자렐토정 (10mg / 15mg / 20mg)", company: "바이엘", category: "항응고제", ingredients: [{ name: "리바록사반", amount: "10~20mg" }] },
  { id: "eliquis", brandName: "엘리퀴스정 (2.5mg / 5mg)", company: "BMS", category: "항응고제", ingredients: [{ name: "아픽사반", amount: "2.5~5mg" }] },
  { id: "lixiana", brandName: "릭시아나정 (15mg / 30mg / 60mg)", company: "한국다이이찌산쿄", category: "항응고제", ingredients: [{ name: "에독사반", amount: "15~60mg" }] },
  { id: "coumadin", brandName: "쿠마딘정 / 와파린정", company: "제일약품", category: "항응고제", ingredients: [{ name: "와파린", amount: "2~5mg" }] },

  // --- 호흡기 / 천식 / 진해거담 처방 전문의약품 (렉시핀, 액시마, 독소마, 아세브론, 코푸, 메프틴 등) ---
  { id: "lexipin", brandName: "렉시핀정 (400mg)", company: "대화제약", category: "기관지확장제/천식 (처방약)", ingredients: [{ name: "독소필린", amount: "400mg" }] },
  { id: "axima", brandName: "액시마정 (400mg)", company: "부광약품", category: "기관지확장제/천식 (처방약)", ingredients: [{ name: "독소필린", amount: "400mg" }] },
  { id: "doxoma", brandName: "독소마정 (400mg)", company: "삼아제약", category: "기관지확장제/천식 (처방약)", ingredients: [{ name: "독소필린", amount: "400mg" }] },
  { id: "andos", brandName: "앤도스정 (400mg)", company: "안국약품", category: "기관지확장제/천식 (처방약)", ingredients: [{ name: "독소필린", amount: "400mg" }] },
  { id: "suropi", brandName: "슈로피정 (400mg)", company: "대원제약", category: "기관지확장제/천식 (처방약)", ingredients: [{ name: "독소필린", amount: "400mg" }] },
  { id: "doxima", brandName: "독시마정 (400mg)", company: "명인제약", category: "기관지확장제/천식 (처방약)", ingredients: [{ name: "독소필린", amount: "400mg" }] },
  { id: "dexiphylline", brandName: "덱시필린정 (400mg)", company: "휴온스", category: "기관지확장제/천식 (처방약)", ingredients: [{ name: "독소필린", amount: "400mg" }] },
  { id: "acebron", brandName: "아세브론정 / 에어브론캡슐", company: "삼아제약/대원제약", category: "기관지확장제 (처방약)", ingredients: [{ name: "아세브로필린", amount: "100mg" }] },
  { id: "theochrono", brandName: "테오크로노서방정 (200mg / 300mg)", company: "보령", category: "기관지확장제 (처방약)", ingredients: [{ name: "테오필린", amount: "200~300mg" }] },
  { id: "uniphyl", brandName: "유니필서방정 (200mg / 400mg)", company: "대웅제약", category: "기관지확장제 (처방약)", ingredients: [{ name: "테오필린", amount: "200~400mg" }] },
  { id: "aminophylline_tab", brandName: "아미노필린정 (100mg)", company: "유한양행", category: "천식/기관지확장 (처방약)", ingredients: [{ name: "아미노필린", amount: "100mg" }] },
  { id: "meptin", brandName: "메프틴정 / 메프틴흡입액", company: "한국오츠카", category: "기관지확장제 (처방약)", ingredients: [{ name: "프로카테롤염산염수화물", amount: "50mcg" }] },
  { id: "atock", brandName: "아토크정 / 삼아아토크건조시럽", company: "삼아제약", category: "기관지확장제 (처방약)", ingredients: [{ name: "포르모테롤", amount: "20~40mcg" }] },
  { id: "hokunalin", brandName: "호쿠날린패치 (0.5mg / 1mg / 2mg)", company: "한국애보트", category: "기관지확장 패치 (처방약)", ingredients: [{ name: "툴로부테롤", amount: "0.5~2mg" }] },
  { id: "notemon", brandName: "노테몬패치", company: "대원제약", category: "기관지확장 패치 (처방약)", ingredients: [{ name: "툴로부테롤", amount: "0.5~2mg" }] },
  { id: "ventolin", brandName: "벤토린에어로솔 / 벤토린흡입액", company: "GSK", category: "급성 천식치료제 (처방약)", ingredients: [{ name: "살부타몰황산염", amount: "100mcg" }] },
  { id: "symbicort", brandName: "심비코트터부헬러 / 라피헬러", company: "아스트라제네카", category: "천식/COPD 흡입제 (처방약)", ingredients: [{ name: "부데소니드", amount: "160mcg" }, { name: "포르모테롤", amount: "4.5mcg" }] },
  { id: "relvar", brandName: "렐바엘립타", company: "GSK", category: "천식/COPD 흡입제 (처방약)", ingredients: [{ name: "빌란테롤트리페나테이트", amount: "25mcg" }, { name: "플루티카손", amount: "100~200mcg" }] },
  { id: "seretide", brandName: "세레타이드디스커스 / 에어로솔", company: "GSK", category: "천식 흡입제 (처방약)", ingredients: [{ name: "살메테롤", amount: "50mcg" }, { name: "플루티카손", amount: "100~500mcg" }] },
  { id: "cofu_tab", brandName: "코푸정 / 코푸시럽", company: "유한양행", category: "진해거담제 (처방약)", ingredients: [{ name: "DL-메틸에페드린", amount: "17.5mg" }, { name: "디히드로코데인타르타르산염", amount: "5mg" }, { name: "클로르페니라민말레산염", amount: "1.5mg" }] },
  { id: "codaewon_forte", brandName: "코대원포르테시럽 / 코대원에스시럽", company: "대원제약", category: "진해거담제 (처방약)", ingredients: [{ name: "DL-메틸에페드린", amount: "13.1mg" }, { name: "디히드로코데인타르타르산염", amount: "5mg" }, { name: "클로르페니라민말레산염", amount: "1.5mg" }] }
];
